"""add modified_at to payments

Revision ID: f7dd86d529cd
Revises: efa0c7e7ebff
Create Date: 2026-01-06 13:35:10.160829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dd86d529cd'
down_revision: Union[str, Sequence[str], None] = 'efa0c7e7ebff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'modified_at')
    # ### end Alembic commands ###
